#! /bin/sh
set -eux
MOCK="mock -r ${OS:-default}"

BIND_MOUNT="--plugin-option=bind_mount:dirs=[(\"$(pwd)\", \"/builddir/cloud-init\")]"

$MOCK --chroot --isolation=simple --unpriv "$BIND_MOUNT" --cwd="/builddir/cloud-init" 'make rpm'
